---
title: "Challenges"
author: "Rohit Rawat"
date: "January 30, 2016"
output: pdf_document
---
<div style="background-color: unset; border: 5px solid;">

__Challenge 2.1__
Goal : to identify the data manipulation actions needed to perform a task

Look at this data:

<!---
produced with
library(knitr)
kable(head(gapminder,50))
--->

|country     | year|      pop|continent | lifeExp| gdpPercap|
|:-----------|----:|--------:|:---------|-------:|---------:|
|Afghanistan | 1952|  8425333|Asia      |  28.801|  779.4453|
|Afghanistan | 1957|  9240934|Asia      |  30.332|  820.8530|
|Afghanistan | 1992| 16317921|Asia      |  41.674|  649.3414|
|Afghanistan | 1997| 22227415|Asia      |  41.763|  635.3414|
|Afghanistan | 2002| 25268405|Asia      |  42.129|  726.7341|
|Afghanistan | 2007| 31889923|Asia      |  43.828|  974.5803|
|Albania     | 1952|  1282697|Europe    |  55.230| 1601.0561|
|Albania     | 1957|  1476505|Europe    |  59.280| 1942.2842|
|Albania     | 1962|  1728137|Europe    |  64.820| 2312.8890|
|Albania     | 1967|  1984060|Europe    |  66.220| 2760.1969|
|Albania     | 1972|  2263554|Europe    |  67.690| 3313.4222|
|Albania     | 1977|  2509048|Europe    |  68.930| 3533.0039|
|Argentina   | 1952| 17876956|Americas  |  62.485| 5911.3151|
|Argentina   | 1957| 19610538|Americas  |  64.399| 6856.8562|


All of this data is loaded into a `data.frame` called `gapminder`. Your boss wants you to compute the average life expectancy over all the years of data available for _Albania_. __Think of what other variables you will need to create to store intermediary results and the final result. Also think about the type each variable will have to be (data.frame, vector, scalar, string?)__. There are many correct answers to this problem. (no code is needed)

</div>

<p style="margin-bottom: 5cm;" />
\newpage

<div style="background-color: unset; border: 5px solid;">

__Challenge 2.2__
Goal : write a basic script

Write and run your own script that will

- Set `x` to 25
- Set `y` to 15
- Calculate the sum and store it in a variable `z`
- print `z`

To start a new script, open the File menu -> New File -> R script. Save it as __`myAdder.R`__ and run it.

</div>


<p style="margin-bottom: 5cm;" />
\newpage

<div style="background-color: unset; border: 5px solid;">

__Challenge 2.3__
Goal : Wrapped function calls.

As we've seen in our print statements, we can use `paste` or `paste0` to concatenate strings.

1. Write a function called `fence` that takes two parameters called `original` and `wrapper` and returns a new string that has the `wrapper` character at the beginning and end of the `original`:

```{r, echo=FALSE}
fence  <-  function(original, wrapper) {
    paste(wrapper, original, wrapper, sep="")
}
```
Example function call and output:
```
fence('name', '---')
---name---
```
</div>

<p style="margin-bottom: 5cm;" />
\newpage

